    
       const grade1 = document.querySelector('#grade1');
       const grade2 = document.querySelector('#grade2');
       const grade3 = document.querySelector('#grade3');
       const grade4 = document.querySelector('#grade4');
       const grade5 = document.querySelector('#grade5');
       const grade6 = document.querySelector('#grade6');
       const grade7 = document.querySelector('#grade7');
       const grade8 = document.querySelector('#grade8');
       const grade9 = document.querySelector('#grade9');
       const grade10 = document.querySelector('#grade10');
       const grade11 = document.querySelector('#grade11');
       const load1 = document.querySelector('#load1');
       const load2 = document.querySelector('#load2');
       const load3 = document.querySelector('#load3');
       const load4 = document.querySelector('#load4');
       const load5 = document.querySelector('#load5');
       const load6 = document.querySelector('#load6');
       const load7 = document.querySelector('#load7');
       const load8 = document.querySelector('#load8');
       const load9 = document.querySelector('#load9');
       const load10 = document.querySelector('#load10');
       const load11 = document.querySelector('#load11');
       Submit.addEventListener('click',() =>{
        const calcCGP = document.querySelector('#submit')
        const point1 = load1.value * grade1.value;
        const point2 = load2.value * grade2.value;
        const point3 = load3.value * grade3.value;
        const point4 = load4.value * grade4.value;
        const point5 = load5.value * grade5.value;
        const point6 = load6.value * grade6.value;
        const point7 = load7.value * grade7.value;
        const point8 = load8.value * grade8.value;
        const point9 = load9.value * grade9.value;
        const point10 = load10.value * grade10.value;
        const point11 = load11.value * grade11.value;
        document.querySelector('#point1').value = point1;
        document.querySelector('#point2').value = point2;
        document.querySelector('#point3').value = point3;
        document.querySelector('#point4').value = point4;
        document.querySelector('#point5').value = point5;
        document.querySelector('#point6').value = point6;
        document.querySelector('#point7').value = point7;
        document.querySelector('#point8').value = point8;
        document.querySelector('#point9').value = point9;
        document.querySelector('#point10').value = point10;
        document.querySelector('#point11').value = point11;
        const totalpoint = point1 + point2 + point3 + point4 + point5 + point6 + point7 + point8 + point9 + point10 + point11;
        const totalload = load1.value*1+load2.value*1+load3.value*1+load4.value*1+load5.value*1+load6.value*1+load7.value*1+load8.value*1+load9.value*1+load10.value*1+load11.value*1; 
        const cgp = totalpoint/totalload;
        const cgp4 = (cgp/5) * 4;

        document.querySelector('#cgpa').value = cgp;
        document.querySelector('#cgpa4').value = cgp4;
    })